language: python
python:
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install coveralls
script:
    - coverage run --source=mdx_truly_sane_lists setup.py test
after_success:
    - coveralls